version: 0.5.{build}

branches:
  only:
    - appveyor

max_jobs: 1

image:
- Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# setting up etc\hosts file
hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - SET KLOG=3
  - curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_msvc17_x64/mkn.exe
  - mkn clean build -dtKOg 0
  - C:\Python36-x64\Scripts\pip install flawfinder
  - C:\Python36-x64\Scripts\flawfinder .
